#!/usr/bin/env python3
"""
高考学习系统 - 批量导入高考英语词汇
导入用户提供的生词列表到数据库
"""

import sqlite3
import json
import os
import sys

# 数据库路径
DB_DIR = os.path.join(os.path.dirname(__file__), '..', 'database')
os.makedirs(DB_DIR, exist_ok=True)
DB_PATH = os.path.join(DB_DIR, 'unified_learning.db')

# 高考英语词汇表（用户提供的生词列表）
VOCABULARY_LIST = [
    {"word": "description", "definition": "n. 描述，描写"},
    {"word": "participant", "definition": "n. 参与者"},
    {"word": "slightly", "definition": "adv. 轻微地，略微地"},
    {"word": "foreigner", "definition": "n. 外国人"},
    {"word": "net", "definition": "n. 网；净得 adj. 净的"},
    {"word": "bite", "definition": "v./n. 咬，叮"},
    {"word": "cigarette", "definition": "n. 香烟"},
    {"word": "deny", "definition": "v. 否认，拒绝"},
    {"word": "outcome", "definition": "n. 结果，成果"},
    {"word": "firm", "definition": "n. 公司 adj. 坚定的，坚固的"},
    {"word": "alcohol", "definition": "n. 酒精，酒"},
    {"word": "gym", "definition": "n. 健身房，体育馆"},
    {"word": "knife", "definition": "n. 刀，餐刀"},
    {"word": "sample", "definition": "n. 样本，样品 v. 品尝"},
    {"word": "threaten", "definition": "v. 威胁，恐吓"},
    {"word": "violin", "definition": "n. 小提琴"},
    {"word": "colleague", "definition": "n. 同事，同僚"},
    {"word": "raincoat", "definition": "n. 雨衣"},
    {"word": "academic", "definition": "adj. 学术的，学院的"},
    {"word": "theirs", "definition": "pron. 他们的（东西）"},
    {"word": "identity", "definition": "n. 身份，特性"},
    {"word": "pale", "definition": "adj. 苍白的，浅的"},
    {"word": "creature", "definition": "n. 生物，动物；人"},
    {"word": "seafood", "definition": "n. 海鲜"},
    {"word": "satellite", "definition": "n. 卫星，人造卫星"},
    {"word": "conflict", "definition": "n. 冲突，矛盾 v. 冲突"},
    {"word": "trend", "definition": "n. 趋势，倾向"},
    {"word": "launch", "definition": "v. 发射，发起，推出"},
    {"word": "loudly", "definition": "adv. 大声地，响亮地"},
    {"word": "golden", "definition": "adj. 金色的，珍贵的"},
    {"word": "tape", "definition": "n. 磁带，胶带，录音带"},
    {"word": "ache", "definition": "v./n. 疼痛"},
    {"word": "associate", "definition": "v. 联系，交往 n. 同事"},
    {"word": "rude", "definition": "adj. 粗鲁的，无礼的"},
    {"word": "indicate", "definition": "v. 表明，指示"},
    {"word": "admission", "definition": "n. 准许进入，承认"},
    {"word": "fool", "definition": "n. 傻瓜 v. 欺骗"},
    {"word": "dolphin", "definition": "n. 海豚"},
    {"word": "cabbage", "definition": "n. 卷心菜，甘蓝"},
    {"word": "dive", "definition": "v./n. 跳水，潜水，跳水式下跌"},
    {"word": "channel", "definition": "n. 频道，渠道，海峡"},
    {"word": "charity", "definition": "n. 慈善，慈善机构"},
    {"word": "pin", "definition": "n. 大头针，别针 v. 钉住"},
    {"word": "ought", "definition": "v. 应该，应当"},
    {"word": "profit", "definition": "n. 利润，利益 v. 有利于"},
    {"word": "part-time", "definition": "adj./adv. 兼职（的）"},
    {"word": "conference", "definition": "n. 会议，讨论会"},
    {"word": "appeal", "definition": "v. 呼吁，吸引 n. 吸引力，上诉"},
    {"word": "opera", "definition": "n. 歌剧"},
    {"word": "fault", "definition": "n. 过错，故障"},
    {"word": "forth", "definition": "adv. 向前，向外"},
    {"word": "poster", "definition": "n. 海报，招贴"},
    {"word": "captain", "definition": "n. 队长，船长，机长"},
    {"word": "guy", "definition": "n. 家伙，男人"},
    {"word": "software", "definition": "n. 软件"},
    {"word": "goose", "definition": "n. 鹅"},
    {"word": "deskmate", "definition": "n. 同桌"},
    {"word": "institute", "definition": "n. 学院，研究所 v. 建立"},
    {"word": "deal", "definition": "v. 处理，交易 n. 交易"},
    {"word": "sink", "definition": "v. 下沉，沉没 n. 水槽"},
    {"word": "jam", "definition": "n. 果酱；堵塞 v. 挤进"},
    {"word": "victim", "definition": "n. 受害者，牺牲品"},
    {"word": "physics", "definition": "n. 物理学"},
    {"word": "issue", "definition": "n. 问题，发行 v. 发行，发布"},
    {"word": "pond", "definition": "n. 池塘"},
    {"word": "dialogue", "definition": "n. 对话，对白"},
    {"word": "zone", "definition": "n. 区域，地带"},
    {"word": "typical", "definition": "adj. 典型的，代表性的"},
    {"word": "closest", "definition": "adj. 最接近的，亲密的"},
    {"word": "ban", "definition": "v./n. 禁止，取缔"},
    {"word": "humor", "definition": "n. 幽默，诙谐"},
    {"word": "excite", "definition": "v. 使兴奋，使激动"},
    {"word": "principle", "definition": "n. 原则，原理"},
    {"word": "sunshine", "definition": "n. 阳光"},
    {"word": "row", "definition": "n. 行，排 v. 划船"},
    {"word": "campaign", "definition": "n. 运动，活动，战役"},
    {"word": "hell", "definition": "n. 地狱，极不愉快的经历"},
    {"word": "motorcycle", "definition": "n. 摩托车"},
    {"word": "indeed", "definition": "adv. 的确，确实"},
    {"word": "carrot", "definition": "n. 胡萝卜"},
    {"word": "unknown", "definition": "adj. 未知的，不出名的"},
    {"word": "somewhat", "definition": "adv. 稍微，有点"},
    {"word": "impact", "definition": "n./v. 影响，冲击"},
    {"word": "commit", "definition": "v. 承诺，犯罪，commit"},
    {"word": "presence", "definition": "n. 出席，存在"},
    {"word": "minus", "definition": "prep. 减，负的 adj. 负的"},
    {"word": "hidden", "definition": "adj. 隐藏的，秘密的"},
    {"word": "policewoman", "definition": "n. 女警察"},
    {"word": "committee", "definition": "n. 委员会"},
    {"word": "code", "definition": "n. 代码，密码，法规"},
    {"word": "volume", "definition": "n. 体积，容量，音量"},
    {"word": "harvest", "definition": "n./v. 收获，收割"},
    {"word": "aside", "definition": "adv. 在旁边，到一边"},
    {"word": "pork", "definition": "n. 猪肉"},
    {"word": "cent", "definition": "n. 分，分币"},
    {"word": "Russian", "definition": "n. 俄国人 adj. 俄罗斯的"},
    {"word": "wallet", "definition": "n. 钱包，皮夹"},
    {"word": "resident", "definition": "n. 居民 adj. 居住的"},
    {"word": "totally", "definition": "adv. 完全地，总共"},
    {"word": "steak", "definition": "n. 牛排，肉排"},
    {"word": "establish", "definition": "v. 建立，确立"},
    {"word": "tax", "definition": "n. 税，税款 v. 征税"},
    {"word": "plain", "definition": "adj. 普通的，清晰的 n. 平原"},
    {"word": "calory", "definition": "n. 卡路里，热量"},
    {"word": "mushroom", "definition": "n. 蘑菇，伞菌"},
    {"word": "reserve", "definition": "v. 保留，预订 n. 储备"},
    {"word": "spaceship", "definition": "n. 宇宙飞船"},
    {"word": "border", "definition": "n. 边界，边境 v. 与…接壤"},
    {"word": "honey", "definition": "n. 蜂蜜，宝贝"},
    {"word": "pill", "definition": "n. 药片，药丸"},
    {"word": "sausage", "definition": "n. 香肠"},
    {"word": "menu", "definition": "n. 菜单"},
    {"word": "salary", "definition": "n. 薪水，工资"},
    {"word": "core", "definition": "n. 核心，果核 adj. 核心的"},
    {"word": "producer", "definition": "n. 生产者，制片人"},
    {"word": "specifically", "definition": "adv. 特别地，明确地"},
    {"word": "cage", "definition": "n. 笼子，牢房 v. 关进笼子"},
    {"word": "discount", "definition": "n. 折扣 v. 打折"},
    {"word": "envelope", "definition": "n. 信封，封套"},
    {"word": "grand", "definition": "adj. 宏伟的，隆重的"},
    {"word": "resolution", "definition": "n. 决心，解决，分辨率"},
    {"word": "bury", "definition": "v. 埋葬，隐藏"},
    {"word": "barely", "definition": "adv. 几乎不，勉强"},
    {"word": "constantly", "definition": "adv. 不断地，时常地"},
    {"word": "union", "definition": "n. 联盟，工会，联合"},
    {"word": "x-ray", "definition": "n. X 射线，X 光"},
    {"word": "chairman", "definition": "n. 主席，董事长"},
    {"word": "essay", "definition": "n. 散文，随笔，论文"},
    {"word": "increasingly", "definition": "adv. 日益，越来越多地"},
    {"word": "beneath", "definition": "prep. 在…下方，在…底下"},
    {"word": "permission", "definition": "n. 允许，许可"},
    {"word": "religion", "definition": "n. 宗教，宗教信仰"},
    {"word": "critical", "definition": "adj. 关键的，批评的"},
    {"word": "decline", "definition": "v. 下降，衰退，婉拒 n. 下降"},
    {"word": "preparation", "definition": "n. 准备，预备"},
    {"word": "beer", "definition": "n. 啤酒"},
    {"word": "poison", "definition": "n. 毒药 v. 毒害"},
    {"word": "debt", "definition": "n. 债务，欠款"},
    {"word": "airline", "definition": "n. 航空公司"},
    {"word": "broadcast", "definition": "v./n. 广播，播放"},
    {"word": "consist", "definition": "v. 组成，构成 (of)"},
    {"word": "roof", "definition": "n. 屋顶，房顶"},
    {"word": "criticize", "definition": "v. 批评，评论"},
    {"word": "ham", "definition": "n. 火腿"},
    {"word": "float", "definition": "v. 漂浮，浮动 n. 漂浮物"},
    {"word": "employ", "definition": "v. 雇用，使用"},
    {"word": "burst", "definition": "v. 爆炸，爆裂 n. 爆发"},
    {"word": "worn", "definition": "adj. 用旧的，磨损的"},
    {"word": "shopper", "definition": "n. 购物者"},
    {"word": "investigation", "definition": "n. 调查，研究"},
    {"word": "her", "definition": "pron. 她的（宾格/所有格）"},
    {"word": "gap", "definition": "n. 缺口，差距，空白"},
    {"word": "highway", "definition": "n. 公路，大路"},
    {"word": "switch", "definition": "v. 切换，转变 n. 开关"},
    {"word": "disability", "definition": "n. 残疾，无能"},
    {"word": "mend", "definition": "v. 修理，修补，改正"},
    {"word": "endangered", "definition": "adj. 濒临灭绝的"},
    {"word": "complaint", "definition": "n. 抱怨，投诉"},
    {"word": "shift", "definition": "v. 转移，变换 n. 轮班"},
    {"word": "drunk", "definition": "adj. 醉的，沉醉的"},
    {"word": "dishonest", "definition": "adj. 不诚实的"},
    {"word": "essential", "definition": "adj. 必要的，基本的"},
    {"word": "physician", "definition": "n. 内科医生"},
    {"word": "basis", "definition": "n. 基础，根据"},
    {"word": "incident", "definition": "n. 事件，事变"},
    {"word": "wave", "definition": "n. 波浪，挥手 v. 挥手"},
    {"word": "gesture", "definition": "n. 手势，姿态"},
    {"word": "employer", "definition": "n. 雇主，老板"},
    {"word": "imply", "definition": "v. 暗示，意味"},
    {"word": "fed", "definition": "feed 的过去式和过去分词"},
    {"word": "nearest", "definition": "adj. 最近的"},
    {"word": "lifetime", "definition": "n. 一生，终身"},
    {"word": "pot", "definition": "n. 锅，壶，罐，大麻"},
    {"word": "toothpaste", "definition": "n. 牙膏"},
    {"word": "album", "definition": "n. 相册，唱片集"},
    {"word": "bully", "definition": "n. 霸凌者 v. 霸凌，欺负"},
    {"word": "universe", "definition": "n. 宇宙，万物"},
    {"word": "tone", "definition": "n. 音调，语气，色调"},
    {"word": "comparison", "definition": "n. 比较，对照"},
    {"word": "vary", "definition": "v. 变化，不同"},
    {"word": "heavily", "definition": "adv. 沉重地，大量地"},
    {"word": "guarantee", "definition": "n./v. 保证，担保"},
    {"word": "weekday", "definition": "n. 工作日"},
    {"word": "shelf", "definition": "n. 架子，搁板"},
    {"word": "elder", "definition": "n. 长者，长辈 adj. 年长的"},
    {"word": "Korean", "definition": "n./adj. 韩国人（的）"},
    {"word": "long-term", "definition": "adj. 长期的"},
    {"word": "guilty", "definition": "adj. 内疚的，有罪的"},
    {"word": "defeat", "definition": "v./n. 击败，战胜"},
    {"word": "listener", "definition": "n. 听众，倾听者"},
    {"word": "depress", "definition": "v. 使沮丧，使萧条"},
    {"word": "precious", "definition": "adj. 珍贵的，宝贵的"},
    {"word": "surf", "definition": "v. 冲浪，浏览网页"},
    {"word": "adjust", "definition": "v. 调整，调节"},
    {"word": "forbidden", "definition": "adj. 禁止的"},
    {"word": "misunderstand", "definition": "v. 误解，误会"},
    {"word": "quantity", "definition": "n. 数量，分量"},
    {"word": "classical", "definition": "adj. 古典的，经典的"},
    {"word": "tick", "definition": "v. 打勾，发出滴答声 n. 记号"},
    {"word": "bush", "definition": "n. 灌木，矮树丛"},
    {"word": "weakness", "definition": "n. 弱点，虚弱"},
    {"word": "jazz", "definition": "n. 爵士乐"},
    {"word": "preserve", "definition": "v. 保护，保存，腌制"},
    {"word": "entertain", "definition": "v. 娱乐，招待"},
    {"word": "neighbourhood", "definition": "n. 街坊，邻近地区"},
    {"word": "scenery", "definition": "n. 风景，景色"},
    {"word": "laptop", "definition": "n. 笔记本电脑"},
    {"word": "Atlantic", "definition": "n./adj. 大西洋（的）"},
    {"word": "click", "definition": "v./n. 点击，发出咔嗒声"},
    {"word": "apparently", "definition": "adv. 显然，表面上"},
    {"word": "DNA", "definition": "n. 脱氧核糖核酸"},
    {"word": "overweight", "definition": "adj. 超重的"},
    {"word": "brief", "definition": "adj. 简短的，简洁的 n. 摘要"},
    {"word": "defend", "definition": "v. 防御，保卫，辩护"},
    {"word": "suspect", "definition": "v. 怀疑 n. 嫌疑人"},
    {"word": "unpleasant", "definition": "adj. 不愉快的，讨厌的"},
    {"word": "disappointment", "definition": "n. 失望，扫兴"},
    {"word": "tent", "definition": "n. 帐篷"},
    {"word": "liquid", "definition": "n. 液体 adj. 液体的"},
    {"word": "commercial", "definition": "adj. 商业的 n. 广告"},
    {"word": "property", "definition": "n. 财产，地产，特性"},
    {"word": "physically", "definition": "adv. 身体上，物理上"},
    {"word": "extend", "definition": "v. 延长，扩展"},
    {"word": "peer", "definition": "n. 同龄人，贵族 v. 凝视"},
    {"word": "unlike", "definition": "prep. 不像 adj. 不同的"},
    {"word": "alternative", "definition": "n. 替代品 adj. 供选择的"},
    {"word": "loan", "definition": "n. 贷款，借款"},
    {"word": "loneliness", "definition": "n. 孤独，寂寞"},
    {"word": "astonish", "definition": "v. 使惊讶"},
    {"word": "reliable", "definition": "adj. 可靠的，可信赖的"},
    {"word": "spite", "definition": "n. 恶意，怨恨"},
    {"word": "expo", "definition": "n. 博览会，展览会"},
    {"word": "instance", "definition": "n. 例子，情况"},
    {"word": "firework", "definition": "n. 烟花，焰火"},
    {"word": "vs.", "definition": "prep. 对，与…相对"},
    {"word": "load", "definition": "v. 装载，加载 n. 负荷"},
    {"word": "bean", "definition": "n. 豆类，豆子"},
    {"word": "significant", "definition": "adj. 重要的，显著的"},
    {"word": "consume", "definition": "v. 消耗，消费"},
    {"word": "study", "definition": "v. 学习，研究 n. 学习，书房"},
    {"word": "rarely", "definition": "adv. 很少，罕见地"},
    {"word": "acknowledge", "definition": "v. 承认，致谢"},
    {"word": "budget", "definition": "n. 预算 v. 做预算"},
    {"word": "fashionable", "definition": "adj. 流行的，时髦的"},
    {"word": "poverty", "definition": "n. 贫穷，贫困"},
    {"word": "engage", "definition": "v. 从事，订婚，吸引"},
    {"word": "studio", "definition": "n. 工作室，演播室"},
    {"word": "illegal", "definition": "adj. 非法的"},
    {"word": "sensitive", "definition": "adj. 敏感的，灵敏的"},
    {"word": "convenience", "definition": "n. 便利，方便"},
    {"word": "fairly", "definition": "adv. 相当地，公平地"},
    {"word": "lung", "definition": "n. 肺"},
    {"word": "suicide", "definition": "n. 自杀"},
    {"word": "fund", "definition": "n. 资金，基金 v. 资助"},
    {"word": "terrorify", "definition": "v. 使恐怖，使害怕"},
    {"word": "extreme", "definition": "adj. 极端的 n. 极端"},
    {"word": "immediate", "definition": "adj. 立即的，直接的"},
    {"word": "independence", "definition": "n. 独立，自主"},
    {"word": "severe", "definition": "adj. 严重的，严厉的"},
    {"word": "file", "definition": "n. 文件，档案，锉刀 v. 归档"},
    {"word": "definition", "definition": "n. 定义，清晰度"},
    {"word": "encouragement", "definition": "n. 鼓励，鼓舞"},
    {"word": "overseas", "definition": "adj./adv. 海外（的）"},
    {"word": "violent", "definition": "adj. 暴力的，猛烈的"},
    {"word": "ease", "definition": "n. 安逸，舒适 v. 减轻"},
    {"word": "proposal", "definition": "n. 提议，建议，求婚"},
    {"word": "jog", "definition": "v. 慢跑，轻推"},
    {"word": "industrial", "definition": "adj. 工业的"},
    {"word": "belt", "definition": "n. 腰带，带子，区域"},
    {"word": "bitter", "definition": "adj. 苦的，痛苦的"},
    {"word": "maintain", "definition": "v. 维持，保养，坚持"},
    {"word": "punishment", "definition": "n. 惩罚，处罚"},
    {"word": "backward", "definition": "adj./adv. 向后的（地）"},
    {"word": "interrupt", "definition": "v. 打断，中断"},
    {"word": "element", "definition": "n. 元素，要素"},
    {"word": "regulation", "definition": "n. 规章，条例，管理"},
    {"word": "motor", "definition": "n. 发动机，马达"},
    {"word": "journalist", "definition": "n. 记者，新闻工作者"},
    {"word": "nutrition", "definition": "n. 营养，营养学"},
    {"word": "waitress", "definition": "n. 女服务员"},
    {"word": "layer", "definition": "n. 层，层次"},
    {"word": "shadow", "definition": "n. 影子，阴影"},
    {"word": "instant", "definition": "adj. 立即的，速食的 n. 瞬间"},
    {"word": "visible", "definition": "adj. 可见的"},
    {"word": "hunter", "definition": "n. 猎人，搜寻者"},
    {"word": "pursue", "definition": "v. 追求，追赶"},
    {"word": "version", "definition": "n. 版本，说法"},
    {"word": "pace", "definition": "n. 步伐，速度 v. 踱步"},
    {"word": "involvement", "definition": "n. 参与，牵连"},
    {"word": "psychological", "definition": "adj. 心理的"},
    {"word": "aloud", "definition": "adv. 出声地，大声地"},
    {"word": "rapidly", "definition": "adv. 迅速地，快速地"},
    {"word": "equally", "definition": "adv. 平等地，同样地"},
    {"word": "doubtful", "definition": "adj. 可疑的，不确定的"},
    {"word": "penfriend", "definition": "n. 笔友"},
    {"word": "container", "definition": "n. 容器，集装箱"},
    {"word": "command", "definition": "v./n. 命令，指挥"},
    {"word": "majority", "definition": "n. 大多数"},
    {"word": "status", "definition": "n. 地位，状态，身份"},
    {"word": "affair", "definition": "n. 事务，事情"},
    {"word": "climber", "definition": "n. 登山者，攀登者"},
    {"word": "yoga", "definition": "n. 瑜伽"},
    {"word": "platform", "definition": "n. 平台，站台，月台"},
    {"word": "flexible", "definition": "adj. 灵活的，柔韧的"},
    {"word": "altogether", "definition": "adv. 总共，总而言之"},
    {"word": "tense", "definition": "adj. 紧张的 v. 拉紧 n. 时态"},
    {"word": "radiation", "definition": "n. 辐射，放射线"},
    {"word": "obesity", "definition": "n. 肥胖，肥胖症"},
    {"word": "politician", "definition": "n. 政治家，政客"},
    {"word": "accomplish", "definition": "v. 完成，实现"},
    {"word": "phenomenon", "definition": "n. 现象"},
    {"word": "candidate", "definition": "n. 候选人，申请者"},
    {"word": "artificial", "definition": "adj. 人工的，人造的"},
    {"word": "scan", "definition": "v. 扫描，浏览 n. 扫描"},
    {"word": "roommate", "definition": "n. 室友"},
    {"word": "tube", "definition": "n. 管子，地铁，电子管"},
    {"word": "error", "definition": "n. 错误，差错"},
    {"word": "full-time", "definition": "adj./adv. 全职（的）"},
    {"word": "infect", "definition": "v. 感染，传染"},
    {"word": "giantly", "definition": "adv. 巨大地"},
    {"word": "curiosity", "definition": "n. 好奇心"},
    {"word": "quiz", "definition": "n. 小测验，问答比赛"},
    {"word": "haven", "definition": "n. 安全的地方，避难所"},
    {"word": "update", "definition": "v./n. 更新"},
    {"word": "AIDS", "definition": "n. 艾滋病"},
    {"word": "acceptable", "definition": "adj. 可接受的"},
    {"word": "interpretation", "definition": "n. 解释，演绎"},
    {"word": "smoker", "definition": "n. 吸烟者"},
    {"word": "whisper", "definition": "v./n. 耳语，低语"},
    {"word": "propose", "definition": "v. 提议，求婚，打算"},
    {"word": "workshop", "definition": "n. 车间，工作室，研讨会"},
    {"word": "salesman", "definition": "n. 销售员"},
    {"word": "okay", "definition": "adj./adv./n. 好，行，可以"},
    {"word": "beautifully", "definition": "adv. 美丽地，漂亮地"},
    {"word": "facial", "definition": "adj. 面部的"},
    {"word": "constant", "definition": "adj. 持续的，恒定的"},
    {"word": "remote", "definition": "adj. 遥远的，远程的"},
    {"word": "spider", "definition": "n. 蜘蛛"},
    {"word": "option", "definition": "n. 选择，选项"},
    {"word": "beneficial", "definition": "adj. 有益的，有利的"},
    {"word": "bargain", "definition": "n. 便宜货 v. 讨价还价"},
    {"word": "van", "definition": "n. 货车，面包车"},
    {"word": "talented", "definition": "adj. 有才华的"},
    {"word": "seller", "definition": "n. 卖方，销售者"},
    {"word": "unnecessary", "definition": "adj. 不必要的"},
    {"word": "agent", "definition": "n. 代理人，经纪人"},
    {"word": "unfamiliar", "definition": "adj. 不熟悉的"},
    {"word": "unwise", "definition": "adj. 不明智的"},
    {"word": "eraser", "definition": "n. 橡皮擦"},
    {"word": "labor", "definition": "n. 劳动，劳工，分娩"},
    {"word": "grown-up", "definition": "n. 成年人 adj. 成人的"},
    {"word": "burnt", "definition": "adj. 烧焦的，烧伤的"},
    {"word": "faith", "definition": "n. 信念，信仰，信任"},
    {"word": "reputation", "definition": "n. 名声，声誉"},
    {"word": "existence", "definition": "n. 存在，生存"},
    {"word": "weapon", "definition": "n. 武器"},
    {"word": "recognition", "definition": "n. 识别，承认"},
    {"word": "drum", "definition": "n. 鼓，鼓声"},
    {"word": "combination", "definition": "n. 结合，联合，组合"},
    {"word": "eagle", "definition": "n. 鹰"},
    {"word": "globe", "definition": "n. 地球，地球仪，球体"},
    {"word": "teaspoon", "definition": "n. 茶匙"},
    {"word": "lamp", "definition": "n. 灯"},
    {"word": "forecast", "definition": "v./n. 预测，预报"},
    {"word": "relatively", "definition": "adv. 相对地"},
    {"word": "barrier", "definition": "n. 障碍，屏障"},
    {"word": "breast", "definition": "n. 胸部，乳房"},
    {"word": "surfing", "definition": "n. 冲浪运动"},
    {"word": "tight", "definition": "adj. 紧的，紧密的"},
    {"word": "jar", "definition": "n. 罐子，广口瓶"},
    {"word": "stock", "definition": "n. 股票，库存 adj. 现货的"},
    {"word": "personally", "definition": "adv. 亲自地，个人地"},
    {"word": "cast", "definition": "v. 投掷，铸造，投射 n. 演员阵容"},
    {"word": "sunset", "definition": "n. 日落"},
    {"word": "publisher", "definition": "n. 出版者，出版社"},
    {"word": "exposure", "definition": "n. 暴露，曝光"},
    {"word": "parkour", "definition": "n. 跑酷"},
    {"word": "construct", "definition": "v. 建造，构造 n. 构想"},
    {"word": "complicated", "definition": "adj. 复杂的"},
    {"word": "someday", "definition": "adv. 有朝一日"},
    {"word": "creation", "definition": "n. 创造，作品"},
    {"word": "elect", "definition": "v. 选举，选择"},
    {"word": "bind", "definition": "v. 捆绑，约束，装订"},
    {"word": "cautious", "definition": "adj. 谨慎的，小心的"},
    {"word": "voyage", "definition": "n. 航行，航海 v. 航行"},
    {"word": "lottery", "definition": "n. 彩票，抽奖"},
    {"word": "luggage", "definition": "n. 行李"},
    {"word": "enormous", "definition": "adj. 巨大的，庞大的"},
    {"word": "upper", "definition": "adj. 上面的，上部的"},
    {"word": "frustrate", "definition": "v. 使沮丧，使灰心"},
    {"word": "enthusiasm", "definition": "n. 热情，热忱"},
    {"word": "costume", "definition": "n. 服装，戏装"},
    {"word": "slave", "definition": "n. 奴隶，苦工 v. 苦干"},
    {"word": "dug", "definition": "dig 的过去式和过去分词"},
    {"word": "initial", "definition": "adj. 最初的，开始的 n. 首字母"},
    {"word": "appendix", "definition": "n. 附录，阑尾"},
    {"word": "absence", "definition": "n. 缺席，不在"},
    {"word": "deep", "definition": "adj. 深的，深刻的"},
    {"word": "bake", "definition": "v. 烤，烘焙"},
    {"word": "charm", "definition": "n. 魅力，魔力 v. 吸引"},
    {"word": "originally", "definition": "adv. 最初，原先"},
    {"word": "buyer", "definition": "n. 买方，购买者"},
    {"word": "bench", "definition": "n. 长凳，工作台"},
    {"word": "moreover", "definition": "adv. 而且，此外"},
    {"word": "romantic", "definition": "adj. 浪漫的"},
    {"word": "ministry", "definition": "n. 部，政府部门"},
    {"word": "forgetful", "definition": "adj. 健忘的"},
    {"word": "spoil", "definition": "v. 溺爱，糟蹋，掠夺"},
    {"word": "appreciation", "definition": "n. 欣赏，感激"},
    {"word": "labour", "definition": "n. 劳动，劳工，分娩"},
    {"word": "possess", "definition": "v. 拥有，具有"},
    {"word": "criticism", "definition": "n. 批评，评论"},
    {"word": "philosophy", "definition": "n. 哲学，人生观"},
    {"word": "extraordinary", "definition": "adj. 非凡的，特别的"},
    {"word": "cart", "definition": "n. 手推车，马车 v. 用车装载"},
    {"word": "hopeful", "definition": "adj. 有希望的"},
    {"word": "qualification", "definition": "n. 资格，学历"},
    {"word": "Chinatown", "definition": "n. 唐人街"},
    {"word": "oneself", "definition": "pron. 自己，自身"},
    {"word": "finance", "definition": "n. 财政，金融 v. 资助"},
    {"word": "qualify", "definition": "v. 使具有资格，胜任"},
    {"word": "downtown", "definition": "n./adj./adv. 市中心（的）"},
    {"word": "accuse", "definition": "v. 指责，控告"},
    {"word": "infection", "definition": "n. 感染，传染病"},
    {"word": "scarf", "definition": "n. 围巾，披巾"},
    {"word": "fountain", "definition": "n. 喷泉，泉水"},
    {"word": "sew", "definition": "v. 缝纫，缝制"},
    {"word": "pedestrian", "definition": "n. 行人 adj. 徒步的"},
    {"word": "drought", "definition": "n. 干旱，旱灾"},
    {"word": "caffeine", "definition": "n. 咖啡因"},
    {"word": "raw", "definition": "adj. 生的，未加工的"},
    {"word": "stuff", "definition": "n. 东西，材料 v. 塞满"},
    {"word": "opponent", "definition": "n. 对手，反对者"},
    {"word": "opposition", "definition": "n. 反对，敌对"},
    {"word": "justify", "definition": "v. 证明…正当，为…辩解"},
    {"word": "import", "definition": "v./n. 进口，输入"},
    {"word": "profession", "definition": "n. 职业，专业"},
    {"word": "typically", "definition": "adv. 典型地，通常"},
    {"word": "motivation", "definition": "n. 动机，动力"},
    {"word": "enjoyment", "definition": "n. 享受，乐趣"},
    {"word": "telescope", "definition": "n. 望远镜"},
    {"word": "drag", "definition": "v. 拖，拉，拽"},
    {"word": "bomb", "definition": "n. 炸弹 v. 轰炸"},
    {"word": "chase", "definition": "v./n. 追逐，追赶"},
    {"word": "joint", "definition": "adj. 联合的 n. 关节"},
    {"word": "bent", "definition": "adj. 弯曲的 bend 的过去式"},
    {"word": "landscape", "definition": "n. 风景，地貌 v. 美化环境"},
    {"word": "wipe", "definition": "v. 擦，擦拭，消除"},
    {"word": "summary", "definition": "n. 摘要，总结 adj. 简快的"},
    {"word": "salty", "definition": "adj. 咸的，含盐的"},
    {"word": "characterize", "definition": "v. 描绘…特性，具有…特征"},
    {"word": "crack", "definition": "v. 破裂，裂开 n. 裂缝"},
    {"word": "visual", "definition": "adj. 视觉的，可视的"},
    {"word": "territory", "definition": "n. 领土，版图，领域"},
    {"word": "password", "definition": "n. 密码，口令"},
    {"word": "bleed", "definition": "v. 流血，出血"},
    {"word": "inn", "definition": "n. 小旅馆，客栈"},
    {"word": "vital", "definition": "adj. 至关重要的，生机勃勃的"},
    {"word": "quilt", "definition": "n. 被子，棉被"},
    {"word": "quote", "definition": "v. 引用，报价 n. 引文"},
    {"word": "watermelon", "definition": "n. 西瓜"},
    {"word": "aircraft", "definition": "n. 飞机，飞行器"},
    {"word": "leadership", "definition": "n. 领导能力，领导阶层"},
    {"word": "dramatic", "definition": "adj. 戏剧的，引人注目的"},
    {"word": "kindergarden", "definition": "n. 幼儿园"},
    {"word": "pat", "definition": "v. 轻拍 n. 轻拍"},
    {"word": "performer", "definition": "n. 表演者"},
    {"word": "diabetes", "definition": "n. 糖尿病"},
    {"word": "mineral", "definition": "n. 矿物质 adj. 矿物的"},
    {"word": "convert", "definition": "v. 转变，转换，皈依"},
    {"word": "fossil", "definition": "n. 化石"},
    {"word": "share", "definition": "v. 分享，共有 n. 份额，股票"},
    {"word": "index", "definition": "n. 索引，指数，指标"},
    {"word": "cheek", "definition": "n. 面颊，脸蛋"},
    {"word": "wage", "definition": "n. 工资，报酬"},
    {"word": "membership", "definition": "n. 会员资格，会员身份"},
    {"word": "merely", "definition": "adv. 仅仅，只不过"},
    {"word": "executive", "definition": "n. 主管，行政官 adj. 行政的"},
    {"word": "traveller", "definition": "n. 旅行者"},
    {"word": "sensor", "definition": "n. 传感器"},
    {"word": "puppy", "definition": "n. 小狗，幼犬"},
    {"word": "bookshop", "definition": "n. 书店"},
    {"word": "temporary", "definition": "adj. 暂时的，临时的"},
    {"word": "westerner", "definition": "n. 西方人"},
    {"word": "rating", "definition": "n. 等级，评分"},
    {"word": "reuse", "definition": "v. 再使用，重复利用"},
    {"word": "relevant", "definition": "adj. 相关的，切题的"},
    {"word": "investor", "definition": "n. 投资者"},
    {"word": "specialize", "definition": "v. 专攻，专门研究"},
    {"word": "advocate", "definition": "v. 提倡，主张 n. 拥护者"},
    {"word": "firefighter", "definition": "n. 消防员"},
    {"word": "fireworks", "definition": "n. 烟花表演"},
    {"word": "frequent", "definition": "adj. 频繁的，经常的"},
    {"word": "pyramid", "definition": "n. 金字塔"},
    {"word": "man-made", "definition": "adj. 人造的"},
    {"word": "parenting", "definition": "n. 养育子女"},
    {"word": "capable", "definition": "adj. 有能力的，有才能的"},
    {"word": "remarkable", "definition": "adj. 非凡的，显著的"},
    {"word": "detect", "definition": "v. 发现，探测"},
    {"word": "tablet", "definition": "n. 药片，平板电脑"},
    {"word": "poorly", "definition": "adv. 差劲地，贫穷地"},
    {"word": "shortcoming", "definition": "n. 缺点，短处"},
    {"word": "assignment", "definition": "n. 任务，作业，分配"},
    {"word": "penny", "definition": "n. 便士，分"},
    {"word": "fog", "definition": "n. 雾"},
    {"word": "funeral", "definition": "n. 葬礼"},
    {"word": "disagreement", "definition": "n. 分歧，不一致"},
    {"word": "edit", "definition": "v. 编辑，剪辑"},
    {"word": "nut", "definition": "n. 坚果，螺母"},
    {"word": "fake", "definition": "adj. 假的，伪造的 v. 伪装 n. 假货"},
    {"word": "temper", "definition": "n. 脾气，情绪"},
    {"word": "thirds", "definition": "n. 三分之一"},
    {"word": "brick", "definition": "n. 砖，砖块"},
    {"word": "fantasy", "definition": "n. 幻想，想象"},
    {"word": "wounded", "definition": "adj. 受伤的"},
    {"word": "orbit", "definition": "n. 轨道 v. 绕轨道运行"},
    {"word": "thrill", "definition": "n. 兴奋，激动 v. 使激动"},
    {"word": "proof", "definition": "n. 证据，证明"},
    {"word": "secretly", "definition": "adv. 秘密地"},
    {"word": "transition", "definition": "n. 过渡，转变"},
    {"word": "affordable", "definition": "adj. 负担得起的"},
    {"word": "bucket", "definition": "n. 水桶，吊桶"},
    {"word": "destruction", "definition": "n. 破坏，毁灭"},
    {"word": "instructor", "definition": "n. 教练，指导员"},
    {"word": "chew", "definition": "v. 咀嚼，嚼碎"},
    {"word": "distinguish", "definition": "v. 区分，辨别"},
    {"word": "uncertain", "definition": "adj. 不确定的"},
    {"word": "jungle", "definition": "n. 丛林，荒地"},
    {"word": "fierce", "definition": "adj. 凶猛的，激烈的"},
    {"word": "type", "definition": "n. 类型 v. 打字"},
    {"word": "ambulance", "definition": "n. 救护车"},
    {"word": "explosion", "definition": "n. 爆炸，爆发"},
    {"word": "avenue", "definition": "n. 大街，林荫道"},
    {"word": "recite", "definition": "v. 背诵，朗诵"},
    {"word": "abuse", "definition": "v./n. 滥用，虐待，辱骂"},
    {"word": "election", "definition": "n. 选举，竞选"},
    {"word": "similarity", "definition": "n. 相似，类似"},
    {"word": "quake", "definition": "n. 地震，震动"},
    {"word": "secondly", "definition": "adv. 第二，其次"},
    {"word": "fundamental", "definition": "adj. 基本的，根本的"},
    {"word": "agenda", "definition": "n. 议程，日程"},
    {"word": "diploma", "definition": "n. 文凭，毕业证书"},
    {"word": "organ", "definition": "n. 器官，风琴，机构"},
    {"word": "builder", "definition": "n. 建造者，建筑工人"},
    {"word": "youngster", "definition": "n. 年轻人，少年"},
    {"word": "gratitude", "definition": "n. 感激，感恩"},
    {"word": "alert", "definition": "adj. 警觉的 n. 警报 v. 警告"},
    {"word": "leather", "definition": "n. 皮革，皮制品"},
    {"word": "chapter", "definition": "n. 章，回，分会"},
    {"word": "operator", "definition": "n. 操作员，话务员"},
    {"word": "miracle", "definition": "n. 奇迹"},
    {"word": "bid", "definition": "v./n. 出价，投标"},
    {"word": "unidentified", "definition": "adj. 未经确认的"},
    {"word": "revision", "definition": "n. 修订，复习"},
    {"word": "spokesman", "definition": "n. 发言人"},
    {"word": "tragedy", "definition": "n. 悲剧，惨案"},
    {"word": "well-being", "definition": "n. 幸福，安康"},
    {"word": "occasionally", "definition": "adv. 偶尔，有时"},
    {"word": "exit", "definition": "n. 出口 v. 退出"},
    {"word": "tutor", "definition": "n. 导师，家庭教师 v. 辅导"},
    {"word": "observation", "definition": "n. 观察，观测"},
    {"word": "marathon", "definition": "n. 马拉松比赛"},
    {"word": "millionaire", "definition": "n. 百万富翁"},
    {"word": "craft", "definition": "n. 工艺，手艺，飞行器"},
    {"word": "cable", "definition": "n. 电缆，缆绳，有线电视"},
    {"word": "nuts", "definition": "n. 坚果类；疯子"},
    {"word": "helper", "definition": "n. 助手，帮手"},
    {"word": "military", "definition": "adj. 军事的 n. 军队"},
    {"word": "whistle", "definition": "n. 哨子 v. 吹口哨"},
    {"word": "actual", "definition": "adj. 实际的，真实的"},
    {"word": "circus", "definition": "n. 马戏团，圆形广场"},
    {"word": "overlook", "definition": "v. 忽视，俯瞰"},
    {"word": "institution", "definition": "n. 机构，制度"},
    {"word": "efficiency", "definition": "n. 效率，效能"},
    {"word": "tobacco", "definition": "n. 烟草，烟叶"},
    {"word": "conservative", "definition": "adj. 保守的 n. 保守派"},
    {"word": "videotape", "definition": "n. 录像带"},
    {"word": "aquarium", "definition": "n. 水族馆"},
    {"word": "scholar", "definition": "n. 学者，奖学金获得者"},
    {"word": "nerve", "definition": "n. 神经，勇气"},
    {"word": "pose", "definition": "v. 摆姿势，造成 n. 姿势"},
    {"word": "publication", "definition": "n. 出版，出版物"},
    {"word": "brilliant", "definition": "adj. 杰出的，精彩的"},
    {"word": "donkey", "definition": "n. 驴"},
    {"word": "defense", "definition": "n. 防御，保卫"},
    {"word": "artistic", "definition": "adj. 艺术的，有美感的"},
    {"word": "Mexican", "definition": "n./adj. 墨西哥人（的）"},
    {"word": "substance", "definition": "n. 物质，实质"},
    {"word": "wetland", "definition": "n. 湿地"},
    {"word": "diverse", "definition": "adj. 不同的，多种多样的"},
    {"word": "wireless", "definition": "adj. 无线的"},
    {"word": "mammal", "definition": "n. 哺乳动物"},
    {"word": "accustom", "definition": "v. 使习惯"},
    {"word": "tribe", "definition": "n. 部落，宗族"},
    {"word": "scar", "definition": "n. 伤疤，伤痕"},
    {"word": "club", "definition": "n. 俱乐部，社团，棍棒"},
    {"word": "gallery", "definition": "n. 画廊，美术馆"},
    {"word": "worthwhile", "definition": "adj. 值得的"},
    {"word": "oven", "definition": "n. 烤箱，炉"},
    {"word": "heritage", "definition": "n. 遗产，传统"},
    {"word": "pancake", "definition": "n. 烙饼，薄煎饼"},
    {"word": "primarily", "definition": "adv. 主要地，首先"},
    {"word": "immune", "definition": "adj. 免疫的，豁免的"},
    {"word": "stubborn", "definition": "adj. 顽固的，倔强的"},
    {"word": "congress", "definition": "n. 国会，代表大会"},
    {"word": "pineapple", "definition": "n. 菠萝"},
    {"word": "scope", "definition": "n. 范围，视野，余地"},
    {"word": "e-book", "definition": "n. 电子书"},
    {"word": "after-school", "definition": "adj. 课外的"},
    {"word": "modest", "definition": "adj. 谦虚的，适度的"},
    {"word": "carnival", "definition": "n. 嘉年华，狂欢节"},
    {"word": "bug", "definition": "n. 虫子，故障，窃听器"},
    {"word": "gardener", "definition": "n. 园丁"},
    {"word": "ladder", "definition": "n. 梯子，阶梯"},
    {"word": "tortoise", "definition": "n. 乌龟"},
    {"word": "deadline", "definition": "n. 截止日期，最后期限"},
    {"word": "consistent", "definition": "adj. 一致的，连续的"},
    {"word": "lawn", "definition": "n. 草坪，草地"},
    {"word": "flavor", "definition": "n. 味道，风味"},
    {"word": "tropical", "definition": "adj. 热带的"},
    {"word": "boyfriend", "definition": "n. 男朋友"},
    {"word": "typhoon", "definition": "n. 台风"},
    {"word": "vet", "definition": "n. 兽医"},
    {"word": "pump", "definition": "n. 泵 v. 抽水，用泵送"},
    {"word": "participation", "definition": "n. 参与，参加"},
    {"word": "birthplace", "definition": "n. 出生地"},
    {"word": "insight", "definition": "n. 洞察力，领悟"},
    {"word": "tuition", "definition": "n. 学费，教学"},
    {"word": "vegetarian", "definition": "n. 素食者 adj. 素食的"},
    {"word": "anniversary", "definition": "n. 周年纪念日"},
    {"word": "sincerely", "definition": "adv. 真诚地"},
    {"word": "significance", "definition": "n. 意义，重要性"},
    {"word": "sometime", "definition": "adv. 某个时候 adj. 以前的"},
    {"word": "middle-aged", "definition": "adj. 中年的"},
    {"word": "shorten", "definition": "v. 缩短，变短"},
    {"word": "rainfall", "definition": "n. 降雨量，降雨"},
    {"word": "weaken", "definition": "v. 减弱，削弱"},
    {"word": "royal", "definition": "adj. 皇家的，王室的"},
    {"word": "deed", "definition": "n. 行为，契约"},
    {"word": "imitate", "definition": "v. 模仿，仿效"},
    {"word": "strangely", "definition": "adv. 奇怪地"},
    {"word": "landmark", "definition": "n. 地标，里程碑"},
    {"word": "helpless", "definition": "adj. 无助的，无能为力的"},
    {"word": "ceiling", "definition": "n. 天花板，上限"},
    {"word": "intense", "definition": "adj. 强烈的，紧张的"},
    {"word": "guideline", "definition": "n. 指导方针，准则"},
    {"word": "enrich", "definition": "v. 使丰富，使富足"},
    {"word": "dominate", "definition": "v. 支配，占优势"},
    {"word": "coverage", "definition": "n. 覆盖范围，新闻报道"},
    {"word": "disappointedly", "definition": "adv. 失望地"},
    {"word": "scold", "definition": "v. 责骂，训斥"},
    {"word": "dependent", "definition": "adj. 依赖的，从属的"},
    {"word": "formation", "definition": "n. 形成，构造"},
    {"word": "breakthrough", "definition": "n. 突破，突破性进展"},
    {"word": "reduction", "definition": "n. 减少，缩小"},
    {"word": "refresh", "definition": "v. 刷新，使恢复"},
    {"word": "flame", "definition": "n. 火焰，热情"},
    {"word": "nail", "definition": "n. 指甲，钉子 v. 钉住"},
    {"word": "prospect", "definition": "n. 前景，前途，景象"},
    {"word": "sculpture", "definition": "n. 雕塑，雕刻"},
    {"word": "cruise", "definition": "n./v. 巡游，巡航"},
    {"word": "minor", "definition": "adj. 较小的，次要的"},
    {"word": "sustainable", "definition": "adj. 可持续的"},
    {"word": "spill", "definition": "v. 溢出，洒出 n. 洒出"},
    {"word": "numerous", "definition": "adj. 众多的，许多的"},
    {"word": "traditionally", "definition": "adv. 传统地"},
    {"word": "farmland", "definition": "n. 农田，耕地"},
    {"word": "sigh", "definition": "v./n. 叹息，叹气"},
    {"word": "makeup", "definition": "n. 化妆品，组成，补考"},
    {"word": "occupation", "definition": "n. 职业，占有"},
    {"word": "provider", "definition": "n. 供应者，提供者"},
    {"word": "unclear", "definition": "adj. 不清楚的"},
    {"word": "pillow", "definition": "n. 枕头"},
    {"word": "Arab", "definition": "n./adj. 阿拉伯人（的）"},
    {"word": "troublesome", "definition": "adj. 麻烦的，讨厌的"},
    {"word": "regain", "definition": "v. 重新获得，恢复"},
    {"word": "recreation", "definition": "n. 娱乐，消遣"},
    {"word": "essentially", "definition": "adv. 本质上，基本上"},
    {"word": "mummy", "definition": "n. 木乃伊，妈妈"},
    {"word": "pronoun", "definition": "n. 代词"},
    {"word": "bull", "definition": "n. 公牛，牛市"},
    {"word": "needle", "definition": "n. 针，针头"},
    {"word": "flour", "definition": "n. 面粉"},
    {"word": "automobile", "definition": "n. 汽车"},
    {"word": "regional", "definition": "adj. 地区的，局部的"},
    {"word": "emphasis", "definition": "n. 强调，重点"},
    {"word": "convict", "definition": "v. 定罪 n. 囚犯"},
    {"word": "isolate", "definition": "v. 隔离，孤立"},
    {"word": "nationwide", "definition": "adj./adv. 全国性的（地）"},
    {"word": "capsule", "definition": "n. 胶囊，太空舱"},
    {"word": "twist", "definition": "v. 扭曲，扭转 n. 转折"},
    {"word": "toast", "definition": "n. 吐司，祝酒 v. 烤面包"},
    {"word": "satisfactory", "definition": "adj. 令人满意的"},
    {"word": "fairytale", "definition": "n. 童话故事"},
    {"word": "retail", "definition": "n./v. 零售"},
    {"word": "PC", "definition": "n. 个人电脑"},
    {"word": "barbecue", "definition": "n. 烧烤 v. 烧烤"},
    {"word": "convention", "definition": "n. 大会，惯例，传统"},
    {"word": "Briton", "definition": "n. 英国人"},
    {"word": "cafeteria", "definition": "n. 自助餐厅"},
    {"word": "undermine", "definition": "v. 破坏，削弱"},
    {"word": "conventional", "definition": "adj. 传统的，常规的"},
    {"word": "diversity", "definition": "n. 多样性，差异"},
    {"word": "conscious", "definition": "adj. 意识到的，有意识的"},
    {"word": "self-respect", "definition": "n. 自尊"},
    {"word": "ridiculous", "definition": "adj. 荒谬的，可笑的"},
    {"word": "flavour", "definition": "n. 味道，风味"},
    {"word": "patch", "definition": "n. 补丁，小块地 v. 修补"},
    {"word": "centimeter", "definition": "n. 厘米"},
    {"word": "boundary", "definition": "n. 边界，界限"},
    {"word": "nightmare", "definition": "n. 噩梦"},
    {"word": "wool", "definition": "n. 羊毛，毛线"},
    {"word": "romance", "definition": "n. 浪漫，爱情小说"},
    {"word": "vase", "definition": "n. 花瓶"},
    {"word": "portrait", "definition": "n. 肖像，画像"},
    {"word": "confidently", "definition": "adv. 自信地"},
    {"word": "skillful", "definition": "adj. 熟练的，灵巧的"},
    {"word": "signature", "definition": "n. 签名，署名"},
    {"word": "navy", "definition": "n. 海军，藏青色"},
    {"word": "sake", "definition": "n. 缘故，理由，日本酒"},
    {"word": "guardian", "definition": "n. 监护人，守卫者"},
    {"word": "commission", "definition": "n. 委员会，佣金，委托"},
    {"word": "privilege", "definition": "n. 特权，优待"},
    {"word": "cottage", "definition": "n. 小屋，村舍"},
    {"word": "reproduce", "definition": "v. 繁殖，复制，再生"},
    {"word": "metre", "definition": "n. 米，公尺"},
    {"word": "neglect", "definition": "v./n. 忽视，忽略"},
    {"word": "unconscious", "definition": "adj. 无意识的，失去知觉的"},
    {"word": "enforcement", "definition": "n. 执行，强制"},
    {"word": "generosity", "definition": "n. 慷慨，大方"},
    {"word": "Roman", "definition": "n./adj. 罗马人（的）"},
    {"word": "crawl", "definition": "v. 爬行，匍匐前进"},
    {"word": "gorilla", "definition": "n. 大猩猩"},
    {"word": "evolve", "definition": "v. 进化，发展"},
    {"word": "fate", "definition": "n. 命运，天数"},
    {"word": "attribute", "definition": "v. 归因于 n. 属性"},
    {"word": "literally", "definition": "adv. 照字面地，确实地"},
    {"word": "governor", "definition": "n. 州长，统治者"},
    {"word": "experimental", "definition": "adj. 实验的，试验性的"},
    {"word": "swell", "definition": "v. 膨胀，肿胀"},
    {"word": "diner", "definition": "n. 用餐者，小餐馆"},
    {"word": "dimension", "definition": "n. 尺寸，维度"},
    {"word": "perceive", "definition": "v. 感知，理解"},
    {"word": "bunch", "definition": "n. 一束，一群 v. 集中"},
    {"word": "walker", "definition": "n. 步行者，散步者"},
    {"word": "compromise", "definition": "n./v. 妥协，折中"},
    {"word": "gram", "definition": "n. 克"},
    {"word": "changeable", "definition": "adj. 可改变的，易变的"},
    {"word": "corruption", "definition": "n. 腐败，贪污"},
    {"word": "grassland", "definition": "n. 草原，草地"},
    {"word": "asset", "definition": "n. 资产，财产，优点"},
    {"word": "grader", "definition": "n. 分级机，评分者"},
    {"word": "mandarin", "definition": "n. 普通话，柑橘"},
    {"word": "oral", "definition": "adj. 口头的，口服的"},
    {"word": "skeleton", "definition": "n. 骨骼，骨架"},
    {"word": "bloom", "definition": "v. 开花 n. 花"},
    {"word": "tattoo", "definition": "n. 纹身，刺青"},
    {"word": "seemingly", "definition": "adv. 表面上，似乎"},
    {"word": "sincere", "definition": "adj. 真诚的，诚挚的"},
    {"word": "fingerprint", "definition": "n. 指纹"},
    {"word": "parachute", "definition": "n. 降落伞"},
    {"word": "internal", "definition": "adj. 内部的，内心的"},
    {"word": "biography", "definition": "n. 传记"},
    {"word": "tireless", "definition": "adj. 不知疲倦的"},
    {"word": "massive", "definition": "adj. 巨大的，大量的"},
    {"word": "carpenter", "definition": "n. 木匠"},
    {"word": "sharply", "definition": "adv. 急剧地，锋利地"},
    {"word": "nonprofit", "definition": "adj. 非营利的"},
    {"word": "nearer", "definition": "adj. 更近的"},
    {"word": "conquer", "definition": "v. 征服，战胜"},
    {"word": "mild", "definition": "adj. 温和的，轻微的"},
    {"word": "continuously", "definition": "adv. 连续不断地"},
    {"word": "camper", "definition": "n. 野营者，露营车"},
    {"word": "restrict", "definition": "v. 限制，约束"},
    {"word": "malaria", "definition": "n. 疟疾"},
    {"word": "bubble", "definition": "n. 气泡，泡沫 v. 冒泡"},
    {"word": "caller", "definition": "n. 来电者，呼叫者"},
    {"word": "scratch", "definition": "v. 抓，划 n. 抓痕"},
    {"word": "curly", "definition": "adj. 卷曲的"},
    {"word": "limitation", "definition": "n. 限制，局限性"},
    {"word": "vaccine", "definition": "n. 疫苗"},
    {"word": "howl", "definition": "v. 嚎叫，咆哮"},
    {"word": "rhyme", "definition": "n. 韵，押韵"},
    {"word": "tournament", "definition": "n. 比赛，锦标赛"},
    {"word": "dairy", "definition": "n. 乳制品，乳品店"},
    {"word": "daylight", "definition": "n. 日光，白昼"},
    {"word": "regretful", "definition": "adj. 后悔的，遗憾的"},
    {"word": "intake", "definition": "n. 吸入，摄取，输入"},
    {"word": "mama", "definition": "n. 妈妈"},
    {"word": "fearful", "definition": "adj. 害怕的，可怕的"},
    {"word": "blogger", "definition": "n. 博客作者"},
    {"word": "aboard", "definition": "adv./prep. 在船（车）上"},
    {"word": "hydrogen", "definition": "n. 氢"},
    {"word": "philosopher", "definition": "n. 哲学家"},
    {"word": "memorable", "definition": "adj. 难忘的，值得纪念的"},
    {"word": "smelt", "definition": "smell 的过去式；v. 冶炼"},
    {"word": "weakly", "definition": "adv. 虚弱地"},
    {"word": "accountant", "definition": "n. 会计师"},
    {"word": "repay", "definition": "v. 偿还，回报"},
    {"word": "pre-reading", "definition": "n. 预读"},
    {"word": "crystal", "definition": "n. 水晶，晶体"},
    {"word": "healthily", "definition": "adv. 健康地"},
    {"word": "imaginary", "definition": "adj. 想象的，虚构的"},
    {"word": "proven", "definition": "adj. 被证实的"},
    {"word": "infant", "definition": "n. 婴儿 adj. 婴儿的"},
    {"word": "innovation", "definition": "n. 创新，革新"},
    {"word": "forgiveness", "definition": "n. 宽恕，原谅"},
    {"word": "basement", "definition": "n. 地下室，底层"},
    {"word": "gadget", "definition": "n. 小装置，小玩意儿"},
    {"word": "cola", "definition": "n. 可乐"},
    {"word": "astronomer", "definition": "n. 天文学家"},
    {"word": "petrol", "definition": "n. 汽油"},
    {"word": "Santa", "definition": "n. 圣诞老人"},
    {"word": "refrigerator", "definition": "n. 冰箱"},
    {"word": "ox", "definition": "n. 牛，公牛"},
    {"word": "tease", "definition": "v. 取笑，逗弄"},
    {"word": "flashlight", "definition": "n. 手电筒"},
    {"word": "brightly", "definition": "adv. 明亮地，鲜明地"},
    {"word": "potentially", "definition": "adv. 潜在地"},
    {"word": "economist", "definition": "n. 经济学家"},
    {"word": "thunder", "definition": "n. 雷，雷声 v. 打雷"},
    {"word": "librarian", "definition": "n. 图书管理员"},
    {"word": "monument", "definition": "n. 纪念碑，纪念物"},
    {"word": "whomever", "definition": "pron. 无论谁（宾格）"},
    {"word": "accurately", "definition": "adv. 精确地"},
    {"word": "separation", "definition": "n. 分离，分开"},
    {"word": "baggage", "definition": "n. 行李"},
    {"word": "loser", "definition": "n. 失败者，输家"},
    {"word": "vivid", "definition": "adj. 生动的，鲜明的"},
    {"word": "guidebook", "definition": "n. 指南，手册"},
    {"word": "cyber", "definition": "adj. 网络的，计算机的"},
    {"word": "ally", "definition": "n. 同盟国，盟友"},
    {"word": "substitute", "definition": "n. 替代品 v. 代替"},
    {"word": "strip", "definition": "v. 剥去，脱掉 n. 条带"},
    {"word": "structural", "definition": "adj. 结构的，建筑的"},
    {"word": "footstep", "definition": "n. 脚步，足迹"},
    {"word": "dawn", "definition": "n. 黎明，拂晓"},
    {"word": "hop", "definition": "v. 跳跃，单脚跳"},
    {"word": "adulthood", "definition": "n. 成年"},
    {"word": "encounter", "definition": "v./n. 遭遇，遇到"},
    {"word": "bounce", "definition": "v. 弹跳，反弹"},
    {"word": "ie", "definition": "adv. 即，也就是"},
    {"word": "diagram", "definition": "n. 图表，图解"},
    {"word": "briefly", "definition": "adv. 简短地，暂时地"},
    {"word": "skim", "definition": "v. 浏览，掠过 n. 撇去"},
    {"word": "semester", "definition": "n. 学期"},
    {"word": "sh", "definition": "int. 嘘（让人安静）"},
    {"word": "tag", "definition": "n. 标签，标记"},
    {"word": "cuisine", "definition": "n. 菜肴，烹饪"},
    {"word": "profile", "definition": "n. 轮廓，简介，侧面"},
    {"word": "novelist", "definition": "n. 小说家"},
    {"word": "miner", "definition": "n. 矿工"},
    {"word": "gifted", "definition": "adj. 有天赋的"},
    {"word": "aspirin", "definition": "n. 阿司匹林"},
    {"word": "housewife", "definition": "n. 家庭主妇"},
    {"word": "shelve", "definition": "v. 放在架子上，搁置"},
    {"word": "distraction", "definition": "n. 分心，干扰"},
    {"word": "impatient", "definition": "adj. 不耐烦的"},
    {"word": "barber", "definition": "n. 理发师"},
    {"word": "myth", "definition": "n. 神话，虚构的故事"},
    {"word": "cyclist", "definition": "n. 骑自行车的人"},
    {"word": "English-speaking", "definition": "adj. 说英语的"},
    {"word": "initiative", "definition": "n. 主动性，倡议"},
    {"word": "predicative", "definition": "n./adj. 表语（的）"},
    {"word": "panel", "definition": "n. 面板，小组，仪表盘"},
    {"word": "cite", "definition": "v. 引用，引证"},
    {"word": "exception", "definition": "n. 例外，除外"},
    {"word": "strictly", "definition": "adv. 严格地"},
    {"word": "unlock", "definition": "v. 开锁，解锁"},
    {"word": "boom", "definition": "n. 繁荣，激增 v. 激增"},
    {"word": "high-tech", "definition": "adj. 高科技的"},
    {"word": "cattle", "definition": "n. 牛，家畜"},
    {"word": "random", "definition": "adj. 随机的 n. 随机"},
    {"word": "obstacle", "definition": "n. 障碍，阻碍"},
    {"word": "negotiation", "definition": "n. 谈判，协商"},
    {"word": "owl", "definition": "n. 猫头鹰"},
    {"word": "approximately", "definition": "adv. 大约，近似地"},
    {"word": "countless", "definition": "adj. 无数的"},
    {"word": "orphan", "definition": "n. 孤儿 adj. 孤儿的"},
    {"word": "powder", "definition": "n. 粉末，药粉"},
    {"word": "deposit", "definition": "v. 存放，沉积 n. 存款"},
    {"word": "fulfill", "definition": "v. 实现，完成，满足"},
    {"word": "maximum", "definition": "n. 最大量 adj. 最大的"},
    {"word": "acre", "definition": "n. 英亩"},
    {"word": "closet", "definition": "n. 壁橱，储藏室"},
    {"word": "orchestra", "definition": "n. 管弦乐队"},
    {"word": "lunchtime", "definition": "n. 午餐时间"},
    {"word": "brochure", "definition": "n. 小册子"},
    {"word": "promotion", "definition": "n. 提升，促销"},
    {"word": "rail", "definition": "n. 栏杆，铁轨 v. 抱怨"},
    {"word": "democracy", "definition": "n. 民主，民主制度"},
    {"word": "thumb", "definition": "n. 拇指"},
    {"word": "milligram", "definition": "n. 毫克"},
    {"word": "glacier", "definition": "n. 冰川，冰河"},
    {"word": "trunk", "definition": "n. 树干，后备箱，象鼻"},
    {"word": "longtime", "definition": "adj. 长期的"},
    {"word": "harmony", "definition": "n. 和谐，融洽"},
    {"word": "roller", "definition": "n. 滚筒，滚轴"},
    {"word": "calmly", "definition": "adv. 平静地，冷静地"},
    {"word": "Bible", "definition": "n. 圣经"},
    {"word": "furthermore", "definition": "adv. 此外，而且"},
    {"word": "rumor", "definition": "n. 谣言，传闻"},
    {"word": "kindly", "definition": "adv. 亲切地，和蔼地"},
    {"word": "pianist", "definition": "n. 钢琴家"},
    {"word": "creator", "definition": "n. 创造者，创作者"},
    {"word": "motion", "definition": "n. 运动，动作，手势"},
    {"word": "fetch", "definition": "v. 取来，接来"},
    {"word": "recommendation", "definition": "n. 推荐，建议"},
    {"word": "tune", "definition": "n. 曲调，音调 v. 调音"},
    {"word": "portion", "definition": "n. 部分，一份"},
    {"word": "comfortably", "definition": "adv. 舒适地"},
    {"word": "concrete", "definition": "n. 混凝土 adj. 具体的"},
    {"word": "efficiently", "definition": "adv. 有效地，高效率地"},
    {"word": "favour", "definition": "n. 好感，恩惠，支持"},
    {"word": "voluntary", "definition": "adj. 自愿的，志愿的"},
    {"word": "appetite", "definition": "n. 食欲，胃口"},
    {"word": "face-to-face", "definition": "adj./adv. 面对面（的）"},
    {"word": "hormone", "definition": "n. 激素，荷尔蒙"},
    {"word": "expedition", "definition": "n. 远征，探险队"},
    {"word": "couch", "definition": "n. 沙发"},
    {"word": "technological", "definition": "adj. 技术的，工艺的"},
    {"word": "acceptance", "definition": "n. 接受，接纳"},
    {"word": "curtain", "definition": "n. 窗帘，幕布"},
    {"word": "unfriendly", "definition": "adj. 不友好的"},
    {"word": "auction", "definition": "n./v. 拍卖"},
    {"word": "brake", "definition": "n. 刹车 v. 刹车"},
    {"word": "surgeon", "definition": "n. 外科医生"},
    {"word": "transplant", "definition": "v. 移植 n. 移植手术"},
    {"word": "Celsius", "definition": "adj. 摄氏的"},
    {"word": "offense", "definition": "n. 冒犯，过错"},
    {"word": "interior", "definition": "n. 内部，内地 adj. 内部的"},
    {"word": "i.e.", "definition": "adv. 即，也就是说"},
    {"word": "swan", "definition": "n. 天鹅"},
    {"word": "withdraw", "definition": "v. 撤退，收回，取款"},
    {"word": "footprint", "definition": "n. 脚印，足迹"},
    {"word": "cognitive", "definition": "adj. 认知的，认识的"},
    {"word": "composer", "definition": "n. 作曲家"},
    {"word": "clown", "definition": "n. 小丑"},
    {"word": "tissue", "definition": "n. 组织，纸巾"},
    {"word": "undergraduate", "definition": "n. 本科生 adj. 大学的"},
    {"word": "silently", "definition": "adv. 沉默地，静静地"},
    {"word": "e-waste", "definition": "n. 电子垃圾"},
    {"word": "equality", "definition": "n. 平等，均等"},
    {"word": "audio", "definition": "adj. 音频的，声音的"},
    {"word": "Christian", "definition": "n./adj. 基督徒（的）"},
    {"word": "memorial", "definition": "n. 纪念碑 adj. 纪念的"},
    {"word": "contemporary", "definition": "adj. 当代的，同时代的"},
    {"word": "resume", "definition": "v. 恢复，重新开始"},
    {"word": "mistaken", "definition": "adj. 错误的，弄错的"},
    {"word": "receiver", "definition": "n. 接收者，听筒"},
    {"word": "leap", "definition": "v. 跳跃，飞跃 n. 跳跃"},
    {"word": "empire", "definition": "n. 帝国"},
    {"word": "minimum", "definition": "n. 最小量 adj. 最小的"},
    {"word": "install", "definition": "v. 安装，安装"},
    {"word": "compose", "definition": "v. 组成，作曲"},
    {"word": "fort", "definition": "n. 堡垒，要塞"},
    {"word": "comet", "definition": "n. 彗星"},
    {"word": "instantly", "definition": "adv. 立即，立刻"},
    {"word": "drill", "definition": "n. 钻头，演习 v. 钻孔"},
    {"word": "mature", "definition": "adj. 成熟的，成熟的"},
    {"word": "curriculum", "definition": "n. 课程"},
    {"word": "innocent", "definition": "adj. 无辜的，清白的"},
    {"word": "PhD", "definition": "n. 博士，博士学位"},
    {"word": "automatically", "definition": "adv. 自动地"},
    {"word": "titanic", "definition": "adj. 巨大的"},
    {"word": "pavilion", "definition": "n. 馆，阁，展馆"},
    {"word": "assign", "definition": "v. 分配，指派"},
    {"word": "dump", "definition": "v. 倾倒，丢弃 n. 垃圾场"},
    {"word": "compound", "definition": "n. 化合物，大院 adj. 复合的"},
    {"word": "illustrate", "definition": "v. 说明，阐明，加插图"},
    {"word": "client", "definition": "n. 客户，委托人"},
    {"word": "sidewalk", "definition": "n. 人行道"},
    {"word": "sector", "definition": "n. 部门，扇形"},
    {"word": "cashier", "definition": "n. 出纳员"},
    {"word": "humanity", "definition": "n. 人类，人性，人文"},
    {"word": "world-famous", "definition": "adj. 世界闻名的"},
    {"word": "dismiss", "definition": "v. 解雇，解散，驳回"},
    {"word": "Jurassic", "definition": "adj. 侏罗纪的"},
    {"word": "unimportant", "definition": "adj. 不重要的"},
    {"word": "hybrid", "definition": "n. 混合物，杂交种"},
    {"word": "workmate", "definition": "n. 同事，工友"},
    {"word": "cupboard", "definition": "n. 碗柜，橱柜"},
    {"word": "domestic", "definition": "adj. 国内的，家庭的"},
    {"word": "invisible", "definition": "adj. 看不见的"},
    {"word": "slice", "definition": "n. 片，切片 v. 切开"},
    {"word": "handshake", "definition": "n. 握手"},
    {"word": "approval", "definition": "n. 赞成，批准"},
    {"word": "adequate", "definition": "adj. 足够的，适当的"},
    {"word": "horn", "definition": "n. 角，号角，喇叭"},
    {"word": "so-called", "definition": "adj. 所谓的"},
    {"word": "towel", "definition": "n. 毛巾"},
    {"word": "collapse", "definition": "v./n. 倒塌，崩溃"},
    {"word": "facilitate", "definition": "v. 促进，使便利"},
    {"word": "politeness", "definition": "n. 礼貌，客气"},
    {"word": "hook", "definition": "n. 钩子 v. 钩住"},
    {"word": "unwanted", "definition": "adj. 不想要的"},
    {"word": "cop", "definition": "n. 警察"},
    {"word": "magician", "definition": "n. 魔术师"},
    {"word": "bound", "definition": "adj. 必定的 v. 跳跃"},
    {"word": "blown", "definition": "blow 的过去分词"},
    {"word": "toss", "definition": "v. 抛，掷，扔"},
    {"word": "dose", "definition": "n. 剂量，用量"},
    {"word": "attributive", "definition": "n./adj. 定语（的）"},
    {"word": "pea", "definition": "n. 豌豆"},
    {"word": "feast", "definition": "n. 盛宴，宴会"},
    {"word": "adventurous", "definition": "adj. 喜欢冒险的"},
    {"word": "patiently", "definition": "adv. 耐心地"},
    {"word": "smog", "definition": "n. 烟雾"},
    {"word": "yen", "definition": "n. 日元"},
    {"word": "demonstrate", "definition": "v. 演示，证明，展示"},
    {"word": "liberal", "definition": "adj. 自由的，开明的"},
    {"word": "tiredness", "definition": "n. 疲劳，疲倦"},
    {"word": "anyhow", "definition": "adv. 无论如何，反正"},
    {"word": "leak", "definition": "v. 漏，泄漏 n. 漏洞"},
    {"word": "theft", "definition": "n. 盗窃，失窃"},
    {"word": "tide", "definition": "n. 潮汐，潮流"},
    {"word": "pregnant", "definition": "adj. 怀孕的"},
    {"word": "necessity", "definition": "n. 必要性，必需品"},
    {"word": "impatience", "definition": "n. 不耐烦，急躁"},
    {"word": "considerate", "definition": "adj. 体贴的，考虑周到的"},
    {"word": "halfway", "definition": "adv. 中途 adj. 中途的"},
    {"word": "dialect", "definition": "n. 方言，土语"},
    {"word": "split", "definition": "v. 分裂，分开 n. 裂缝"},
    {"word": "cooler", "definition": "n. 冷却器，冰箱"},
    {"word": "prevention", "definition": "n. 预防，防止"},
    {"word": "questionnaire", "definition": "n. 调查问卷"},
    {"word": "module", "definition": "n. 模块，组件"},
    {"word": "checkout", "definition": "n. 结账，退房"},
    {"word": "schoolmate", "definition": "n. 同学，校友"},
    {"word": "sickness", "definition": "n. 疾病，恶心"},
    {"word": "carve", "definition": "v. 雕刻，切割"},
    {"word": "regulate", "definition": "v. 调节，规定"},
    {"word": "carelessly", "definition": "adv. 粗心地"},
    {"word": "departure", "definition": "n. 离开，出发"},
    {"word": "Re", "definition": "prep. 关于，就…而言"},
    {"word": "diagnose", "definition": "v. 诊断，判断"},
    {"word": "spin", "definition": "v. 旋转，纺纱 n. 旋转"},
    {"word": "weird", "definition": "adj. 怪异的，奇怪的"},
    {"word": "canal", "definition": "n. 运河，渠道"},
    {"word": "minority", "definition": "n. 少数，少数民族"},
    {"word": "extinction", "definition": "n. 灭绝，消失"},
    {"word": "forum", "definition": "n. 论坛，讨论会"},
    {"word": "hence", "definition": "adv. 因此，今后"},
    {"word": "modem", "definition": "n. 调制解调器"},
    {"word": "premier", "definition": "adj. 首要的 n. 总理"},
    {"word": "prayer", "definition": "n. 祈祷，祷告"},
    {"word": "Antarctic", "definition": "adj. 南极的"},
    {"word": "boost", "definition": "v. 促进，增加 n. 提升"},
    {"word": "intellectual", "definition": "n. 知识分子 adj. 智力的"},
    {"word": "high-speed", "definition": "adj. 高速的"},
    {"word": "self-control", "definition": "n. 自制，自控"}
]


def import_vocabulary():
    """批量导入词汇到数据库"""
    # 默认使用用户 ID 1（可根据需要修改）
    user_id = 1

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # 检查用户是否存在（如果不存在则跳过）
    cursor.execute('SELECT id FROM users WHERE id = ?', (user_id,))
    if not cursor.fetchone():
        print(f"警告：用户 ID {user_id} 不存在，无法导入词汇")
        print("提示：请先登录系统创建用户")
        conn.close()
        return

    imported_count = 0
    skipped_count = 0

    for word_data in VOCABULARY_LIST:
        try:
            # 检查单词是否已存在
            cursor.execute('''
                SELECT id FROM vocabulary
                WHERE user_id = ? AND word = ?
            ''', (user_id, word_data['word']))

            if cursor.fetchone():
                skipped_count += 1
                continue

            # 插入新单词
            cursor.execute('''
                INSERT INTO vocabulary
                (user_id, word, definition, status, difficulty_level, 熟练度)
                VALUES (?, ?, ?, ?, ?, ?)
            ''', (
                user_id,
                word_data['word'],
                word_data['definition'],
                'new',
                1,
                0
            ))

            imported_count += 1

            # 每导入 100 条提交一次
            if imported_count % 100 == 0:
                conn.commit()
                print(f"已导入 {imported_count} 个单词...")

        except Exception as e:
            print(f"导入单词 {word_data['word']} 失败：{e}")
            skipped_count += 1

    # 提交剩余数据
    conn.commit()
    conn.close()

    print("\n" + "=" * 50)
    print(f"导入完成!")
    print(f"  成功导入：{imported_count} 个单词")
    print(f"  跳过（已存在）: {skipped_count} 个单词")
    print(f"  总计：{len(VOCABULARY_LIST)} 个单词")
    print("=" * 50)


if __name__ == '__main__':
    print("高考学习系统 - 批量导入高考英语词汇")
    print("=" * 50)
    import_vocabulary()
